name: Deploy Flutter Web to GH Pages
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --dart-define=BACKEND_BASE=${{ secrets.BACKEND_BASE }} --base-href /vitty_onboarding_web/ --web-renderer canvaskit
      - run: cp build/web/index.html build/web/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
